version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.READ_PRIVATE_GITHUB_PACKAGES}}
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 4
    versioning-strategy: increase
    registries:
      - npm-github
    schedule:
      interval: "daily"
    groups:
      lint:
        patterns:
          - "@typescript-eslint/*"
          - "eslint"
          - "eslint-*"
          - "prettier"
    ignore:
      - dependency-name: "@rjsf/core"
        update-types: ["version-update:semver-major"]
      - dependency-name: "material-components-web"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@stencil/core"
      - dependency-name: "jest"
      - dependency-name: "jest-cli"
      - dependency-name: "@types/jest"
      - dependency-name: "puppeteer"
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 5
